export const theme = {
  colorPrimaryBlue: '#130048',
  colorPrimaryAccent: '#FB7A9C',
  colorSecondaryBlue: '#194CAA',
  colorSecondaryAccent: '#2165E3',
  colorDarkGray: '#272D3A',
  colorLightGray: '#F2F2F0',
  colorOrangeSplit: '#FB775E',
  colorWhite: '#FFFFFF',
  colorBlack: '#000000',
  colorTransparent: 'transparent',

  colorSuccess: '#23943d',
  colorError: '#E74236',

  borderRadius4: 4,
  borderRadius8: 8,
  borderRadius12: 12,
  borderRadius32: 32,

  fontBlack: 'Poppins-Black',
  fontBlackItalic: 'Poppins-BlackItalic',
  fontBold: 'Poppins-Bold',
  fontBoldItalic: 'Poppins-BoldItalic',
  fontExtraBold: 'Poppins-ExtraBold',
  fontExtraBoldItalic: 'Poppins-ExtraBoldItalic',
  fontExtraLight: 'Poppins-ExtraLight',
  fontExtraLightItalic: 'Poppins-ExtraLightItalic',
  fontItalic: 'Poppins-Italic',
  fontLight: 'Poppins-Light',
  fontLightItalic: 'Poppins-LightItalic',
  fontMedium: 'Poppins-Medium',
  fontMediumItalic: 'Poppins-MediumItalic',
  fontRegular: 'Poppins-Regular',
  fontSemiBold: 'Poppins-SemiBold',
  fontSemiBoldItalic: 'Poppins-SemiBoldItalic',
  fontThin: 'Poppins-Thin',
  fontThinItalic: 'Poppins-ThinItalic',

  fontSize10: 10,
  fontSize12: 12,
  fontSize14: 14,
  fontSize16: 16,
  fontSize18: 18,
  fontSize20: 20,
  fontSize24: 24,
  fontSize28: 28,
  fontSize32: 32,
  fontSize36: 36,
  fontSize72: 72,

  space1: 1,
  space2: 2,
  space4: 4,
  space8: 8,
  space12: 12,
  space16: 16,
  space20: 20,
  space24: 24,
  space28: 28,
  space32: 32,
  space40: 40,
  space48: 48,
  space56: 56,
  space64: 64,
  space72: 72,

  defaultActiveOpacity: 0.9,
};

export const flex1 = { flex: 1 };
